services:
  frontend:
    platform: linux/arm64
    image: aahilsamnani/quirknotes_frontend
    ports:
      - "3000:80"

  backend:
    platform: linux/arm64
    image: aahilsamnani/quirknotes_backend:latest
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
